idf_component_register(SRCS "main.c"
                       INCLUDE_DIRS "."
                       "../../../host"
                       "../../../host/api/include"
                       "../../../host/core/include/h_public"
                       "../../../host/core/include/h_internal"
                       "../../../host/port/include"
                       "../../../host/port/esp-idf"
                       "../../../common/transport")
